root -l -b -q 'SimToPhysicsConverter.C("HidraSimout_Run0.root")'
root -l -b -q 'SimToPhysicsConverter.C("HidraSimout_Run1.root")'
root -l -b -q 'SimToPhysicsConverter.C("HidraSimout_Run2.root")'
root -l -b -q 'SimToPhysicsConverter.C("HidraSimout_Run3.root")'
root -l -b -q 'SimToPhysicsConverter.C("HidraSimout_Run4.root")'
root -l -b -q 'SimToPhysicsConverter.C("HidraSimout_Run5.root")'
root -l -b -q 'SimToPhysicsConverter.C("HidraSimout_Run6.root")'
